Revert "test pp-win"
This reverts commit 6f5620e51afb2985a7d44137f99465ce44012bf4.

arma_str.hpp(166,33): error C2039: '_snprintf': is not a member of 'std'